# Site settings
author: Jayson Kesterson
title: Software Engineering Blog #1
header-img: img/home-bg.png
email: jayson.kesterson24@gmail.com
copyright_name: Jayson Kesterson
description: > # this means to ignore newlines until "baseurl:"
  Procedural/Object Oriented Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JaysonKesterson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
